# # # # # NOTE TO GITHUB USER # # # # #
# if you are pulling this program to use it, you will not have hangman_words.py or hangman_art.py
# and will need to correct the code, adding your own word list and either deleting the 'print stages' statement
# or creating a list 'stages' with your own artwork
# you might also consider removing the 'from hangman... import ...' lines of code
# # # # # END GITHUB USER NOTE # # # # #



# We are using the random module to select a random word from the word list, so we need to include it here.
import random
# We want to import our 'word list' and our 'stages' drawings from these other programs, which we can do with
# 'from (program) import (list, string, variable, etc name)'.
from hangman_words import word_list
from hangman_art import stages
chosen_word = random.choice(word_list)
# we create a placeholder with the same char amount as the chosen word, showing all blanks, to start the game.
placeholder = ""
for position in range(len(chosen_word)):
    placeholder += "_"

print("Let's Play Hangman!\n")

print("What's the word?: " + placeholder)

# the user starts with six lives. The game is not yet over (which is our while loop condition).
# we use a correct letters list to store what the user has guessed right so far.
lives = 6
game_over = False
correct_letters = []
guessed_letters = []

# while the game isn't over, we are going to have the user guess a letter. this letter gets checked against both the
# correct word and the correct letters list. if it's already been guessed (we see it in correct letters), we tell the
# user it's already been guessed.
while not game_over and lives > 0:
    guess = input("Guess a letter: ").lower()
    if guess in correct_letters:
        print("You already guessed this letter!")
    # we are using a string called 'display', generated each time the loop runs, to show what's been guessed correctly
    # so far and what remains blank. This is generated by checking the users latest guessed letter against the
    # letters in the 'correct word' and the list of 'correct letters' we created earlier.
    display = ""

    for letter in chosen_word:
        if letter == guess:
            display += letter
            correct_letters.append(letter)
        elif letter in correct_letters:
            display += letter
        else:
            display += "_"
    # if the user guesses incorrectly, we decrease their number of lives by a value of 1.
    if guess not in chosen_word:
        lives -= 1

    guessed_letters.append(guess)
    print("So far, you've guessed: ")
    print(guessed_letters)
    print("\nWhat's the word?:  " + display)
    # our 'stages' list is our hangman art, held as strings inside a list (called 'stages'). it's designed to
    # work backwards as lives are decremented down to 0.
    print(stages[lives])

    # if the user guesses everything correctly, they win.
    if "_" not in display:
        game_over = True
        print("You win!")

# if you run out of lives, you lose. This statement must exist outside the 'while loop' or this will not work...
if lives == 0:
    print("You lose! You're out of lives!")
    print("The word was: " + chosen_word)
